{{- if .Values.auth.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo.fullname" . }}-auth
  labels:
    {{- include "neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  ttyd-credential: {{ printf "%s:%s" .Values.auth.username .Values.auth.password | quote }}
{{- end }}
