{{- if .Values.ttyd.credential }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo.fullname" . }}-ttyd
  labels:
    {{- include "neo.labels" . | nindent 4 }}
type: Opaque
stringData:
  credential: {{ .Values.ttyd.credential | quote }}
{{- end }}
