apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo.fullname" . }}-ui
  labels:
    {{- include "neo.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo-ui
spec:
  selector:
    {{- include "neo.selectorLabels" . | nindent 4 }}
  ports:
    - name: neo-ui
      port: {{ .Values.ports.ui }}
      targetPort: neo-ui
      protocol: TCP
